dynamixel_manager:
  ros__parameters:
    namespace: dynamixel_controller_manager
    serial_ports.pantilt.port_name: /dev/ttyUSB0
    serial_ports.pantilt.baud_rate: 1000000
    serial_ports.pantilt.min_motor_id: 1
    serial_ports.pantilt.max_motor_id: 3
    serial_ports.pantilt.update_rate: 10
