FROM hirokiyokoyama/ros-jp42
LABEL maintainer "hirokiyokoyama <h-yokoyama@craft-server.co.jp>"
# install ros tutorials packages
RUN apt-get update && apt-get install -y \
    ros-melodic-robot-state-publisher \
    ros-melodic-dynamixel-controllers \
    ros-melodic-xacro \
    && rm -rf /var/lib/apt/lists/
COPY ./pan_tilt.launch /
COPY ./dynamixel_joint_state_publisher.py /opt/ros/kinetic/lib/robot_state_publisher
COPY ./urdf /urdf

CMD ["roslaunch", "/pan_tilt.launch"]
